-- ─── Seed: Lista base de insumos ────────────────────────────────────────────
-- Ejecutar en Supabase → SQL Editor (usa el rol service_role, bypassa RLS).
-- La columna `codigo` queda NULL por ahora; se puede completar desde la pantalla.

WITH uid AS (
  SELECT id FROM auth.users
  WHERE email = 'capacitacion.costo@gmail.com'
  LIMIT 1
)
INSERT INTO insumos (nombre, unidad_medida, tipo, precio_unitario, user_id)
SELECT v.nombre, v.unidad_medida, v.tipo::tipo_insumo, v.precio_unitario, (SELECT id FROM uid)
FROM (VALUES

  -- ── Mano de obra ──────────────────────────────────────────────────────────
  ('Jornal Básico Oficial',                         'h',    'mano_de_obra',   631.90),
  ('Jornal Básico Ayudante',                        'h',    'mano_de_obra',   197.07),

  -- ── Materiales ────────────────────────────────────────────────────────────
  ('Cemento',                                       'kg',   'material',         6.15),
  ('Arena',                                         'm3',   'material',      2890.00),
  ('Piedra',                                        'm3',   'material',      3520.00),
  ('Hierro torsionado',                             'kg',   'material',      1562.00),
  ('Mallas sold. de Fe tors',                       'kg',   'material',       695.41),
  ('Alambre Negro',                                 'kg',   'material',       298.00),
  ('Madera para encofrado',                         'm2',   'material',       478.00),
  ('Cal',                                           'kg',   'material',         3.90),
  ('Ladrillo Cerámico 8x18x25',                    'u',    'material',        64.56),
  ('Hidrófugo',                                    'kg',   'material',      1662.00),
  ('Techado asfáltico (lts)',                      'l',    'material',       674.50),
  ('Pintura asfáltica',                            'kg',   'material',      1080.00),
  ('Metal desplegado',                              'gl',   'material',       418.85),
  ('Alambre galvanizado Nº 8',                     'kg',   'material',      3055.32),
  ('Clavos',                                        'kg',   'material',       360.00),
  ('Chapa Trapezoidal Nº 24',                      'm2',   'material',      1738.00),
  ('Chapa Trap 1010 Nº 24 Prepintada',             'm2',   'material',       890.00),
  ('Chapa AU L1 400 Nº 24 Galv',                   'm2',   'material',      1114.00),
  ('Correa de hierro Tipo C',                       'm2',   'material',       356.83),
  ('Viga metálica Tipo C',                         'm2',   'material',     13140.00),
  ('Chapa lisa Nº 24 Prepintada',                  'm2',   'material',      5500.00),
  ('Chapa lisa Nº 24 Galv',                        'm2',   'material',      6060.00),
  ('Cumbrera de Chapa Nº 24',                      'm',    'material',      2191.00),
  ('Gancho J para techo',                           'u',    'material',       290.00),
  ('Chapa Galvanizada lisa Nº 27',                 'kg',   'material',      2500.00),
  ('Plegado Chapa',                                 'kg',   'material',       260.00),
  ('Accesorios para zingueria',                     'gl',   'material',       800.00),
  ('Ladrillos comunes',                             'u',    'material',        20.00),
  ('Ladrillos comunes p/visto',                     'u',    'material',       180.00),
  ('Placas de yeso 9,5 mm',                        'm2',   'material',       661.00),
  ('Perfil Galera Chapa electricincada prepintada', 'm',    'material',       139.00),
  ('Perfil L Chapa electricincada prepintada',      'm',    'material',       161.00),
  ('Alambre Galvanizado Nº 13',                    'kg',   'material',      1800.00),
  ('Cascote de ladrillos',                          'm3',   'material',      4500.00),
  ('Lijas y Accesorios',                            'gl',   'material',        45.00),
  ('Entonador x 120 cc',                            'u',    'material',       175.00),
  ('Antióxido',                                    'l',    'material',      1737.00),
  ('Pintura T/Cetol o sim.',                        'l',    'material',      2956.00),
  ('Esmalte sintético',                            'l',    'material',       725.00),
  ('Pintura siliconada p/muros ext',                'l',    'material',      2225.00),
  ('Látex p/interiores',                           'l',    'material',      3120.00),
  ('Látex p/exteriores',                           'l',    'material',      4690.00),
  ('Látex p/cielorrasos',                          'l',    'material',      4796.00),
  ('Pintura a látex p/piletas',                    'l',    'material',      3293.00),
  ('Pintura especial para pizarron',                'l',    'material',       729.00),
  ('Enduido plástico',                             'kg',   'material',      3400.00),
  ('Pintura Epoxi inc. catalizador',                'l',    'material',      3604.00),
  ('Impermeabilizante t/Barrier Aqua',              'l',    'material',      1179.00),
  ('Listón perimetral de 3/4x2"',                  'm',    'material',       196.00),
  ('Listón perimetral de 3/4x4"',                  'm',    'material',       318.00),
  ('Portatiza de madera dura',                      'm',    'material',      1000.00),
  ('Sellador 1º Mano',                             'l',    'material',       439.00),
  ('Acido muriático',                              'l',    'material',      6990.00),
  ('Tornillo de bce c/tacos fischer',               'u',    'material',       765.00),
  ('Vidrio triple transparente 4mm',                'm2',   'material',      1900.00),
  ('Masilla',                                       'kg',   'material',      1775.00),
  ('Ceramicos esmaltados de 20x20',                 'm2',   'material',        75.00),
  ('Cemento Blanco',                                'kg',   'material',      2400.00),
  ('Revestimiento cementicio Texturado simil piedra','kg',  'material',      2000.00),
  ('Adhesivo cementicio p/revest.',                 'kg',   'material',      1300.00),
  ('Brea solida',                                   'kg',   'material',        36.00),
  ('Cera',                                          'kg',   'material',         0.00),
  ('Mosaico Granítico 30x30 Color',                'm2',   'material',       100.00),
  ('Zócalo Granítico 10x30',                       'm',    'material',       380.00),
  ('Pastina color',                                 'kg',   'material',       305.58),
  ('Losetas de 40x40 c/relieves',                   'u',    'material',       190.00),
  ('Losetas de 50x40 Atermico p/borde',             'u',    'material',       412.00),
  ('Sellador de juntas en tiras',                   'm',    'material',       375.00),
  ('Reja metálica',                                'u',    'material',       540.76),
  ('Mortero de cto 1:3',                            'm3',   'material',      1086.00),
  ('Machimbre de 3/4x4"',                          'm2',   'material',       400.00),
  ('Caballetes de pino 1 x 3 1/2"',               'm',    'material',      1000.00),
  ('Listón de pino 1/2 x 1 1/2"',                 'm',    'material',       180.00),
  ('Alfajias de pino 1x3"',                        'm',    'material',        30.00),
  ('Estacas de madera semidura',                    'u',    'material',        30.00),
  ('Cantonera de madera',                           'm',    'material',       200.00),
  ('Clavos s/cabeza',                               'kg',   'material',       236.53),
  ('Lana de vidrio de 38mm',                        'm2',   'material',      4370.00),
  ('Isopor en planchas de 1"',                     'm2',   'material',        86.81),
  ('Alum Air 10 mm',                                'm2',   'material',      3200.00),
  ('Techado asfáltico (m2)',                       'm2',   'material',      2950.00),
  ('Membrana asfáltica con Al de 4mm',              'm2',   'material',      5245.00),
  ('Mesada granito reconstituido',                  'm2',   'material',      5450.00),
  ('Umbrales y solias de granito reconstituido',    'm2',   'material',      6500.00),
  ('Angulos y perfilerías de hierro',              'kg',   'material',      2558.00),
  ('Correas de Chapa negra',                        'kg',   'material',      7932.00),
  ('Correas de Chapa Galvanizadas',                 'kg',   'material',      5200.00),
  ('Perfil normal Nº 8',                           'kg',   'material',      1200.00)

) AS v(nombre, unidad_medida, tipo, precio_unitario);
