-- ─── Seed: Asigna códigos a los insumos ya cargados ─────────────────────────
-- Ejecutar en Supabase → SQL Editor DESPUÉS de haber corrido 001_insumos_base.sql
-- Orden: MO-XX para mano de obra, M-XX para materiales (orden original del ingeniero)

WITH uid AS (
  SELECT id FROM auth.users
  WHERE email = 'capacitacion.costo@gmail.com'
  LIMIT 1
)
UPDATE insumos SET codigo = CASE nombre
  -- Mano de obra
  WHEN 'Jornal Básico Oficial'                          THEN 'MO-01'
  WHEN 'Jornal Básico Ayudante'                         THEN 'MO-02'
  -- Materiales
  WHEN 'Cemento'                                        THEN 'M-01'
  WHEN 'Arena'                                          THEN 'M-02'
  WHEN 'Piedra'                                         THEN 'M-03'
  WHEN 'Hierro torsionado'                              THEN 'M-04'
  WHEN 'Mallas sold. de Fe tors'                        THEN 'M-05'
  WHEN 'Alambre Negro'                                  THEN 'M-06'
  WHEN 'Madera para encofrado'                          THEN 'M-07'
  WHEN 'Cal'                                            THEN 'M-08'
  WHEN 'Ladrillo Cerámico 8x18x25'                     THEN 'M-09'
  WHEN 'Hidrófugo'                                     THEN 'M-10'
  WHEN 'Techado asfáltico (lts)'                       THEN 'M-11'
  WHEN 'Pintura asfáltica'                             THEN 'M-12'
  WHEN 'Metal desplegado'                               THEN 'M-13'
  WHEN 'Alambre galvanizado Nº 8'                      THEN 'M-14'
  WHEN 'Clavos'                                         THEN 'M-15'
  WHEN 'Chapa Trapezoidal Nº 24'                       THEN 'M-16'
  WHEN 'Chapa Trap 1010 Nº 24 Prepintada'              THEN 'M-17'
  WHEN 'Chapa AU L1 400 Nº 24 Galv'                    THEN 'M-18'
  WHEN 'Correa de hierro Tipo C'                        THEN 'M-19'
  WHEN 'Viga metálica Tipo C'                          THEN 'M-20'
  WHEN 'Chapa lisa Nº 24 Prepintada'                   THEN 'M-21'
  WHEN 'Chapa lisa Nº 24 Galv'                         THEN 'M-22'
  WHEN 'Cumbrera de Chapa Nº 24'                       THEN 'M-23'
  WHEN 'Gancho J para techo'                            THEN 'M-24'
  WHEN 'Chapa Galvanizada lisa Nº 27'                  THEN 'M-25'
  WHEN 'Plegado Chapa'                                  THEN 'M-26'
  WHEN 'Accesorios para zingueria'                      THEN 'M-27'
  WHEN 'Ladrillos comunes'                              THEN 'M-28'
  WHEN 'Ladrillos comunes p/visto'                      THEN 'M-29'
  WHEN 'Placas de yeso 9,5 mm'                         THEN 'M-30'
  WHEN 'Perfil Galera Chapa electricincada prepintada'  THEN 'M-31'
  WHEN 'Perfil L Chapa electricincada prepintada'       THEN 'M-32'
  WHEN 'Alambre Galvanizado Nº 13'                     THEN 'M-33'
  WHEN 'Cascote de ladrillos'                           THEN 'M-34'
  WHEN 'Lijas y Accesorios'                             THEN 'M-35'
  WHEN 'Entonador x 120 cc'                             THEN 'M-36'
  WHEN 'Antióxido'                                     THEN 'M-37'
  WHEN 'Pintura T/Cetol o sim.'                         THEN 'M-38'
  WHEN 'Esmalte sintético'                             THEN 'M-39'
  WHEN 'Pintura siliconada p/muros ext'                 THEN 'M-40'
  WHEN 'Látex p/interiores'                            THEN 'M-41'
  WHEN 'Látex p/exteriores'                            THEN 'M-42'
  WHEN 'Látex p/cielorrasos'                           THEN 'M-43'
  WHEN 'Pintura a látex p/piletas'                     THEN 'M-44'
  WHEN 'Pintura especial para pizarron'                 THEN 'M-45'
  WHEN 'Enduido plástico'                              THEN 'M-46'
  WHEN 'Pintura Epoxi inc. catalizador'                 THEN 'M-47'
  WHEN 'Impermeabilizante t/Barrier Aqua'               THEN 'M-48'
  WHEN 'Listón perimetral de 3/4x2"'                   THEN 'M-49'
  WHEN 'Listón perimetral de 3/4x4"'                   THEN 'M-50'
  WHEN 'Portatiza de madera dura'                       THEN 'M-51'
  WHEN 'Sellador 1º Mano'                              THEN 'M-52'
  WHEN 'Acido muriático'                               THEN 'M-53'
  WHEN 'Tornillo de bce c/tacos fischer'                THEN 'M-54'
  WHEN 'Vidrio triple transparente 4mm'                 THEN 'M-55'
  WHEN 'Masilla'                                        THEN 'M-56'
  WHEN 'Ceramicos esmaltados de 20x20'                  THEN 'M-57'
  WHEN 'Cemento Blanco'                                 THEN 'M-58'
  WHEN 'Revestimiento cementicio Texturado simil piedra' THEN 'M-59'
  WHEN 'Adhesivo cementicio p/revest.'                  THEN 'M-60'
  WHEN 'Brea solida'                                    THEN 'M-61'
  WHEN 'Cera'                                           THEN 'M-62'
  WHEN 'Mosaico Granítico 30x30 Color'                 THEN 'M-63'
  WHEN 'Zócalo Granítico 10x30'                        THEN 'M-64'
  WHEN 'Pastina color'                                  THEN 'M-65'
  WHEN 'Losetas de 40x40 c/relieves'                    THEN 'M-66'
  WHEN 'Losetas de 50x40 Atermico p/borde'              THEN 'M-67'
  WHEN 'Sellador de juntas en tiras'                    THEN 'M-68'
  WHEN 'Reja metálica'                                 THEN 'M-69'
  WHEN 'Mortero de cto 1:3'                             THEN 'M-70'
  WHEN 'Machimbre de 3/4x4"'                           THEN 'M-71'
  WHEN 'Caballetes de pino 1 x 3 1/2"'                THEN 'M-72'
  WHEN 'Listón de pino 1/2 x 1 1/2"'                  THEN 'M-73'
  WHEN 'Alfajias de pino 1x3"'                         THEN 'M-74'
  WHEN 'Estacas de madera semidura'                     THEN 'M-75'
  WHEN 'Cantonera de madera'                            THEN 'M-76'
  WHEN 'Clavos s/cabeza'                                THEN 'M-77'
  WHEN 'Lana de vidrio de 38mm'                         THEN 'M-78'
  WHEN 'Isopor en planchas de 1"'                      THEN 'M-79'
  WHEN 'Alum Air 10 mm'                                 THEN 'M-80'
  WHEN 'Techado asfáltico (m2)'                        THEN 'M-81'
  WHEN 'Membrana asfáltica con Al de 4mm'               THEN 'M-82'
  WHEN 'Mesada granito reconstituido'                   THEN 'M-83'
  WHEN 'Umbrales y solias de granito reconstituido'     THEN 'M-84'
  WHEN 'Angulos y perfilerías de hierro'               THEN 'M-85'
  WHEN 'Correas de Chapa negra'                         THEN 'M-86'
  WHEN 'Correas de Chapa Galvanizadas'                  THEN 'M-87'
  WHEN 'Perfil normal Nº 8'                            THEN 'M-88'
  ELSE codigo
END
WHERE user_id = (SELECT id FROM uid);
